# Generated by Django 3.2.9 on 2022-05-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='IsAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='Is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='VehicleTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS_Models.vehicletype'),
        ),
    ]
