# Generated by Django 3.2.9 on 2021-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Package_type_id',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
