# Generated by Django 3.2.9 on 2022-06-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='StateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='TMS_Models.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='CountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='TMS_Models.country'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
    ]
