# Generated by Django 3.2.9 on 2021-12-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0002_auto_20211203_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Package_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TMS_Models.package_type'),
        ),
    ]
