# Generated by Django 3.2.9 on 2022-05-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='AccountTypeId',
            new_name='AccountsTypeId',
        ),
        migrations.AlterField(
            model_name='userauth',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='TMS_Models.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'Other'), ('M', 'Male')], max_length=50, null=True),
        ),
    ]
