# Generated by Django 4.0 on 2021-12-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0002_alter_user_auth_joinnig_date'),
        ('TMS_Models', '0003_package_package_type_id'),
    ]

    operations = [
    ]
