# Generated by Django 3.2.9 on 2022-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0003_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'Other'), ('F', 'Female')], max_length=50, null=True),
        ),
    ]
