# Generated by Django 3.2.9 on 2022-06-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0002_auto_20220611_1728'),
        ('TMS_Models', '0008_alter_users_gender'),
    ]

    operations = [
    ]
