# Generated by Django 3.2.9 on 2022-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0009_merge_0002_auto_20220611_1728_0008_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'Other'), ('M', 'Male')], max_length=50, null=True),
        ),
    ]
