# Generated by Django 3.2.8 on 2021-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='joinnig_date',
            field=models.DateField(null=True),
        ),
    ]
